export const SET_VISIBILITY = 'SET_VISIBILITY'
export const RETRIEVE_SUGGESTIONS = 'RETRIEVE_SUGGESTIONS'
export const RETRIEVE_SUGGESTIONS_SUCCESS = 'RETRIEVE_SUGGESTIONS_SUCCESS'
export const RETRIEVE_SUGGESTIONS_FAILURE = 'RETRIEVE_SUGGESTIONS_FAILURE'

